name: Maven build and Push Docker Image

on:
  push:
    branches:
      - build_docker_push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'  

    - name: Build with Maven
      run: |
        ./mvnw package
        ls -l target
        
    - name: Display Dockerfile
      run: cat dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        # Build Docker image using your existing Dockerfile in the root directory
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t arafathbeevi/docker:latest .


        docker images

        # Push the image to Docker Hub
        docker push arafathbeevi/docker:latest
