name: Maven build and Push Docker Image

on:
  push:
    branches:
      - build_docker_push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'  

    - name: Build with Maven
      run: |
        ./mvnw package      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: arafathbeevi/docker
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        TAG=$(TZ='CET' date +'%d_%m_%Y_%H_%M_%S')
        IMAGE_TAGGED_NAME=$IMAGE_NAME:$TAG
        docker build -t $IMAGE_TAGGED_NAME .
        docker image ls
        docker push $IMAGE_TAGGED_NAME
