name: Maven build and Push Docker Image

on:
  push:
    branches:
      - build_docker_push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'  

    - name: Build with Maven
      run: |
        ./mvnw package
        ls -l target
        
    - name: Display Dockerfile
      run: cat dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: arafathbeevi/docker
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        # Set a specific tag for the Docker image
        TAG=$(date +'%Y%m%d%H%M%S')
        IMAGE_TAGGED_NAME=$IMAGE_NAME:$TAG

        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_TAGGED_NAME .

        docker images

        docker push $IMAGE_TAGGED_NAME
